version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:884551203152:task-definition/Taskdef:1"
        LoadBalancerInfo:
          ContainerName: "Container"
          ContainerPort: 80
        PlatformVersion: "LATEST"
