FROM node:14
WORKDIR /usr/src/app

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG MYSQL_SERVER

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_SERVER=$MYSQL_SERVER

COPY package*.json ./
COPY . .
RUN npm install
EXPOSE 80

CMD sh -c "npx sequelize-cli db:migrate && npm run devstart"